### ISSUE TITLE
Date range not applied, when a category is first chosen for the transactions to be filtered by

### ISSUE THREAD

**Issue by ldash** [adotland/mint-date-range#3]
If the transactions are unfiltered, then the date range is applied and then one can apply additional category filters. But for me, if initially (that's important) applying the category and then turning on the date range filter, then it does not work: I can see the filter values on the URL, but the transactions list is just filtered by the category and not the dates. I'm running latest Chrome on Win7. Can anyone else confirm such behavior?

**Comment by adotland** [comment]
Mint.com made a change in their code that broke the extension. I have a fix for it, and it should be live later today. Thanks
