### ISSUE TITLE
Extension not working anymore

### ISSUE THREAD

**Issue by Oliver84** [adotland/mint-date-range#4]
I entered the dates April 1 - April 30 and this is the URL that I'm getting back:

https://wwws.mint.com/transaction.event##location:%7B%22dateStart%22%3A%224%2F1%2F2016%22%2C%22dateEnd%22%3A%224%2F30%2F2016%22%2C%22query%22%3A%22%22%2C%22offset%22%3A0%2C%22typeFilter%22%3A%22cash%22%7D

This doesn't seem to be working anymore.

**Comment by adotland** [comment]
fixed in latest release. thanks.
