### ISSUE TITLE
Date range extension no longer works due to change in Mint hostname

### ISSUE THREAD

**Issue by bob-atkins** [adotland/mint-date-range#5]
Looks like Intuit has changed the website name for Mint to https://mint.intuit.com/

Now the Mint Date Range extension remains greyed out and cannot be used.

Would be grateful if you could fix this as your extension is very useful.

Thank you,
Bob

**Comment by adotland** [comment]
Fixed in latest commit: https://github.com/adotland/mint-date-range/commit/95eadc41b46299bd27098dd4a6d4121b95fc0299

Thanks!

**Comment by bob-atkins** [comment]
Thank you for the quick fix. Any idea when the updated version will be available to be downloaded for chrome?

**Comment by adotland** [comment]
update is live and should be downloaded to your browser by now
