### ISSUE TITLE
Can't install from Chrome Extensions Store

### ISSUE THREAD

**Issue by IvanExpert** [adotland/mint-date-range#8]
Version 1.6.0, which is what is in the Store has, will not install within Chrome. The following error is displayed instead when attempting to install:

"Package is invalid. Details: 'Could not load icon 'images/mdr-icon-16.png' for page action.'."

The issue appears to be that that all files are at the root level, rather than in folders.

workaround:
download CRX file from Extensions Store (in my case, using Get CRX extension)
convert CRX to zip file (in my case, using https://robwu.nl/crxviewer/)
unzip
make "js" folder and put all .js files in it
make "images" folder and put all image files in it
make "css" folder and put the CSS file in it
enable Developer Mode in Chrome
click Load Unpacked, and select the Mint Date Range folder

**Comment by adotland** [comment]
1.6.1 available now.

Thanks!
